name: Release to Production Jcloudv2

on:
  push:
    branches: [development]
    paths:
      - 'src/**'
  workflow_dispatch:
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        docker login ${{ secrets.HARBOR_REGISTRY_URL }} -u ${{ secrets.HARBOR_REGISTRY_USERNAME }} -p ${{ secrets.HARBOR_REGISTRY_PASSWORD }}     
    
    # Build the Docker image
    - name: Set version tag
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: docker/Dockerfile
        push: true
        tags: ${{ secrets.HARBOR_SERVICE_IMAGENAME }}:
